package net.mouza.security.entity;

import org.springframework.stereotype.Component;


public class OrganizeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize_info.organize_uuid
     *
     * @mbggenerated
     */
    private String organizeUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize_info.organize_parent
     *
     * @mbggenerated
     */
    private String organizeParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize_info.organize_code
     *
     * @mbggenerated
     */
    private String organizeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize_info.organize_name
     *
     * @mbggenerated
     */
    private String organizeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize_info.organize_desc
     *
     * @mbggenerated
     */
    private String organizeDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize_info
     *
     * @mbggenerated
     */
    public OrganizeInfo(String organizeUuid, String organizeParent, String organizeCode, String organizeName, String organizeDesc) {
        this.organizeUuid = organizeUuid;
        this.organizeParent = organizeParent;
        this.organizeCode = organizeCode;
        this.organizeName = organizeName;
        this.organizeDesc = organizeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize_info
     *
     * @mbggenerated
     */
    public OrganizeInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize_info.organize_uuid
     *
     * @return the value of organize_info.organize_uuid
     *
     * @mbggenerated
     */
    public String getOrganizeUuid() {
        return organizeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize_info.organize_uuid
     *
     * @param organizeUuid the value for organize_info.organize_uuid
     *
     * @mbggenerated
     */
    public void setOrganizeUuid(String organizeUuid) {
        this.organizeUuid = organizeUuid == null ? null : organizeUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize_info.organize_parent
     *
     * @return the value of organize_info.organize_parent
     *
     * @mbggenerated
     */
    public String getOrganizeParent() {
        return organizeParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize_info.organize_parent
     *
     * @param organizeParent the value for organize_info.organize_parent
     *
     * @mbggenerated
     */
    public void setOrganizeParent(String organizeParent) {
        this.organizeParent = organizeParent == null ? null : organizeParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize_info.organize_code
     *
     * @return the value of organize_info.organize_code
     *
     * @mbggenerated
     */
    public String getOrganizeCode() {
        return organizeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize_info.organize_code
     *
     * @param organizeCode the value for organize_info.organize_code
     *
     * @mbggenerated
     */
    public void setOrganizeCode(String organizeCode) {
        this.organizeCode = organizeCode == null ? null : organizeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize_info.organize_name
     *
     * @return the value of organize_info.organize_name
     *
     * @mbggenerated
     */
    public String getOrganizeName() {
        return organizeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize_info.organize_name
     *
     * @param organizeName the value for organize_info.organize_name
     *
     * @mbggenerated
     */
    public void setOrganizeName(String organizeName) {
        this.organizeName = organizeName == null ? null : organizeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize_info.organize_desc
     *
     * @return the value of organize_info.organize_desc
     *
     * @mbggenerated
     */
    public String getOrganizeDesc() {
        return organizeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize_info.organize_desc
     *
     * @param organizeDesc the value for organize_info.organize_desc
     *
     * @mbggenerated
     */
    public void setOrganizeDesc(String organizeDesc) {
        this.organizeDesc = organizeDesc == null ? null : organizeDesc.trim();
    }
}