package net.mouza.security.entity;

public class ResourceInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_info.resource_uuid
     *
     * @mbggenerated
     */
    private String resourceUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_info.resource_code
     *
     * @mbggenerated
     */
    private String resourceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_info.resource_name
     *
     * @mbggenerated
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_info.resource_uri
     *
     * @mbggenerated
     */
    private String resourceUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_info.resource_method
     *
     * @mbggenerated
     */
    private String resourceMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_info.organize_uuid
     *
     * @mbggenerated
     */
    private String organizeUuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbggenerated
     */
    public ResourceInfo(String resourceUuid, String resourceCode, String resourceName, String resourceUri, String resourceMethod, String organizeUuid) {
        this.resourceUuid = resourceUuid;
        this.resourceCode = resourceCode;
        this.resourceName = resourceName;
        this.resourceUri = resourceUri;
        this.resourceMethod = resourceMethod;
        this.organizeUuid = organizeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbggenerated
     */
    public ResourceInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_info.resource_uuid
     *
     * @return the value of resource_info.resource_uuid
     * @mbggenerated
     */
    public String getResourceUuid() {
        return resourceUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_info.resource_uuid
     *
     * @param resourceUuid the value for resource_info.resource_uuid
     * @mbggenerated
     */
    public void setResourceUuid(String resourceUuid) {
        this.resourceUuid = resourceUuid == null ? null : resourceUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_info.resource_code
     *
     * @return the value of resource_info.resource_code
     * @mbggenerated
     */
    public String getResourceCode() {
        return resourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_info.resource_code
     *
     * @param resourceCode the value for resource_info.resource_code
     * @mbggenerated
     */
    public void setResourceCode(String resourceCode) {
        this.resourceCode = resourceCode == null ? null : resourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_info.resource_name
     *
     * @return the value of resource_info.resource_name
     * @mbggenerated
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_info.resource_name
     *
     * @param resourceName the value for resource_info.resource_name
     * @mbggenerated
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_info.resource_uri
     *
     * @return the value of resource_info.resource_uri
     * @mbggenerated
     */
    public String getResourceUri() {
        return resourceUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_info.resource_uri
     *
     * @param resourceUri the value for resource_info.resource_uri
     * @mbggenerated
     */
    public void setResourceUri(String resourceUri) {
        this.resourceUri = resourceUri == null ? null : resourceUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_info.resource_method
     *
     * @return the value of resource_info.resource_method
     * @mbggenerated
     */
    public String getResourceMethod() {
        return resourceMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_info.resource_method
     *
     * @param resourceMethod the value for resource_info.resource_method
     * @mbggenerated
     */
    public void setResourceMethod(String resourceMethod) {
        this.resourceMethod = resourceMethod == null ? null : resourceMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_info.organize_uuid
     *
     * @return the value of resource_info.organize_uuid
     * @mbggenerated
     */
    public String getOrganizeUuid() {
        return organizeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_info.organize_uuid
     *
     * @param organizeUuid the value for resource_info.organize_uuid
     * @mbggenerated
     */
    public void setOrganizeUuid(String organizeUuid) {
        this.organizeUuid = organizeUuid == null ? null : organizeUuid.trim();
    }

    @Override
    public String toString() {
        return "ResourceInfo{" +
                "resourceUuid='" + resourceUuid + '\'' + '\n' +
                ", resourceCode='" + resourceCode + '\'' + '\n' +
                ", resourceName='" + resourceName + '\'' + '\n' +
                ", resourceUri='" + resourceUri + '\'' + '\n' +
                ", resourceMethod='" + resourceMethod + '\'' + '\n' +
                ", organizeUuid='" + organizeUuid + '\'' + '\n' +
                '}';
    }
}