package net.mouza.security.entity;

import org.springframework.security.provisioning.InMemoryUserDetailsManager;
import org.springframework.security.provisioning.UserDetailsManager;

public class RoleResourceRelations {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource_relations.record_uuid
     *
     * @mbggenerated
     */
    private String recordUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource_relations.role_uuid
     *
     * @mbggenerated
     */
    private String roleUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource_relations.resource_uuid
     *
     * @mbggenerated
     */
    private String resourceUuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_relations
     *
     * @mbggenerated
     */
    public RoleResourceRelations(String recordUuid, String roleUuid, String resourceUuid) {
        this.recordUuid = recordUuid;
        this.roleUuid = roleUuid;
        this.resourceUuid = resourceUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_relations
     *
     * @mbggenerated
     */
    public RoleResourceRelations() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource_relations.record_uuid
     *
     * @return the value of role_resource_relations.record_uuid
     * @mbggenerated
     */
    public String getRecordUuid() {
        return recordUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource_relations.record_uuid
     *
     * @param recordUuid the value for role_resource_relations.record_uuid
     * @mbggenerated
     */
    public void setRecordUuid(String recordUuid) {
        this.recordUuid = recordUuid == null ? null : recordUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource_relations.role_uuid
     *
     * @return the value of role_resource_relations.role_uuid
     * @mbggenerated
     */
    public String getRoleUuid() {
        return roleUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource_relations.role_uuid
     *
     * @param roleUuid the value for role_resource_relations.role_uuid
     * @mbggenerated
     */
    public void setRoleUuid(String roleUuid) {
        this.roleUuid = roleUuid == null ? null : roleUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource_relations.resource_uuid
     *
     * @return the value of role_resource_relations.resource_uuid
     * @mbggenerated
     */
    public String getResourceUuid() {
        return resourceUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource_relations.resource_uuid
     *
     * @param resourceUuid the value for role_resource_relations.resource_uuid
     * @mbggenerated
     */
    public void setResourceUuid(String resourceUuid) {
        this.resourceUuid = resourceUuid == null ? null : resourceUuid.trim();
    }


    @Override
    public String toString() {
        return "RoleResourceRelations{" +
                "recordUuid='" + recordUuid + '\'' +
                ", roleUuid='" + roleUuid + '\'' +
                ", resourceUuid='" + resourceUuid + '\'' +
                '}';
    }
}