package net.mouza.security.entity;

public class StationInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_info.station_uuid
     *
     * @mbggenerated
     */
    private String stationUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_info.station_code
     *
     * @mbggenerated
     */
    private String stationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_info.station_name
     *
     * @mbggenerated
     */
    private String stationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_info.station_desc
     *
     * @mbggenerated
     */
    private String stationDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_info
     *
     * @mbggenerated
     */
    public StationInfo(String stationUuid, String stationCode, String stationName, String stationDesc) {
        this.stationUuid = stationUuid;
        this.stationCode = stationCode;
        this.stationName = stationName;
        this.stationDesc = stationDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_info
     *
     * @mbggenerated
     */
    public StationInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_info.station_uuid
     *
     * @return the value of station_info.station_uuid
     *
     * @mbggenerated
     */
    public String getStationUuid() {
        return stationUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_info.station_uuid
     *
     * @param stationUuid the value for station_info.station_uuid
     *
     * @mbggenerated
     */
    public void setStationUuid(String stationUuid) {
        this.stationUuid = stationUuid == null ? null : stationUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_info.station_code
     *
     * @return the value of station_info.station_code
     *
     * @mbggenerated
     */
    public String getStationCode() {
        return stationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_info.station_code
     *
     * @param stationCode the value for station_info.station_code
     *
     * @mbggenerated
     */
    public void setStationCode(String stationCode) {
        this.stationCode = stationCode == null ? null : stationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_info.station_name
     *
     * @return the value of station_info.station_name
     *
     * @mbggenerated
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_info.station_name
     *
     * @param stationName the value for station_info.station_name
     *
     * @mbggenerated
     */
    public void setStationName(String stationName) {
        this.stationName = stationName == null ? null : stationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_info.station_desc
     *
     * @return the value of station_info.station_desc
     *
     * @mbggenerated
     */
    public String getStationDesc() {
        return stationDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_info.station_desc
     *
     * @param stationDesc the value for station_info.station_desc
     *
     * @mbggenerated
     */
    public void setStationDesc(String stationDesc) {
        this.stationDesc = stationDesc == null ? null : stationDesc.trim();
    }
}