package net.mouza.security.entity;

public class UserOrganizeRelations {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organize_relations.record_uuid
     *
     * @mbggenerated
     */
    private String recordUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organize_relations.user_uuid
     *
     * @mbggenerated
     */
    private String userUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organize_relations.organize_uuid
     *
     * @mbggenerated
     */
    private String organizeUuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organize_relations
     *
     * @mbggenerated
     */
    public UserOrganizeRelations(String recordUuid, String userUuid, String organizeUuid) {
        this.recordUuid = recordUuid;
        this.userUuid = userUuid;
        this.organizeUuid = organizeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organize_relations
     *
     * @mbggenerated
     */
    public UserOrganizeRelations() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organize_relations.record_uuid
     *
     * @return the value of user_organize_relations.record_uuid
     *
     * @mbggenerated
     */
    public String getRecordUuid() {
        return recordUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organize_relations.record_uuid
     *
     * @param recordUuid the value for user_organize_relations.record_uuid
     *
     * @mbggenerated
     */
    public void setRecordUuid(String recordUuid) {
        this.recordUuid = recordUuid == null ? null : recordUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organize_relations.user_uuid
     *
     * @return the value of user_organize_relations.user_uuid
     *
     * @mbggenerated
     */
    public String getUserUuid() {
        return userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organize_relations.user_uuid
     *
     * @param userUuid the value for user_organize_relations.user_uuid
     *
     * @mbggenerated
     */
    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid == null ? null : userUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organize_relations.organize_uuid
     *
     * @return the value of user_organize_relations.organize_uuid
     *
     * @mbggenerated
     */
    public String getOrganizeUuid() {
        return organizeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organize_relations.organize_uuid
     *
     * @param organizeUuid the value for user_organize_relations.organize_uuid
     *
     * @mbggenerated
     */
    public void setOrganizeUuid(String organizeUuid) {
        this.organizeUuid = organizeUuid == null ? null : organizeUuid.trim();
    }
}