package net.mouza.security.entity;

public class UserRoleRelations {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_relations.record_uuid
     *
     * @mbggenerated
     */
    private String recordUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_relations.user_uuid
     *
     * @mbggenerated
     */
    private String userUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_relations.role_uuid
     *
     * @mbggenerated
     */
    private String roleUuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relations
     *
     * @mbggenerated
     */
    public UserRoleRelations(String recordUuid, String userUuid, String roleUuid) {
        this.recordUuid = recordUuid;
        this.userUuid = userUuid;
        this.roleUuid = roleUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relations
     *
     * @mbggenerated
     */
    public UserRoleRelations() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_relations.record_uuid
     *
     * @return the value of user_role_relations.record_uuid
     * @mbggenerated
     */
    public String getRecordUuid() {
        return recordUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relations.record_uuid
     *
     * @param recordUuid the value for user_role_relations.record_uuid
     * @mbggenerated
     */
    public void setRecordUuid(String recordUuid) {
        this.recordUuid = recordUuid == null ? null : recordUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_relations.user_uuid
     *
     * @return the value of user_role_relations.user_uuid
     * @mbggenerated
     */
    public String getUserUuid() {
        return userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relations.user_uuid
     *
     * @param userUuid the value for user_role_relations.user_uuid
     * @mbggenerated
     */
    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid == null ? null : userUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_relations.role_uuid
     *
     * @return the value of user_role_relations.role_uuid
     * @mbggenerated
     */
    public String getRoleUuid() {
        return roleUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relations.role_uuid
     *
     * @mbggenerated
     */
    public void setRoleUuid(String roleUuid) {
        this.roleUuid = roleUuid == null ? null : roleUuid.trim();
    }
}