package net.mouza.security.dao;

import net.mouza.security.entity.OrganizeInfo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface OrganizeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String organizeUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize_info
     *
     * @mbggenerated
     */
    int insert(OrganizeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize_info
     *
     * @mbggenerated
     */
    int insertSelective(OrganizeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize_info
     *
     * @mbggenerated
     */
    OrganizeInfo selectByPrimaryKey(String organizeUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrganizeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrganizeInfo record);

    List<OrganizeInfo> lists();
}