package net.mouza.security.dao;

import net.mouza.security.entity.ResourceInfo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ResourceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String resourceUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbggenerated
     */
    int insert(ResourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbggenerated
     */
    int insertSelective(ResourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbggenerated
     */
    ResourceInfo selectByPrimaryKey(String resourceUuid);

    ResourceInfo selectByUri(String uri);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ResourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ResourceInfo record);

    List<ResourceInfo> lists();




}