package net.mouza.security.dao;

import net.mouza.security.entity.RoleResourceRelations;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface RoleResourceRelationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_relations
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String recordUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_relations
     *
     * @mbggenerated
     */
    int insert(RoleResourceRelations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_relations
     *
     * @mbggenerated
     */
    int insertSelective(RoleResourceRelations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_relations
     *
     * @mbggenerated
     */
    RoleResourceRelations selectByPrimaryKey(String recordUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_relations
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleResourceRelations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_relations
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleResourceRelations record);

    List<RoleResourceRelations> lists();

    List<RoleResourceRelations> selectByRelations(RoleResourceRelations record);
}