package net.mouza.security.dao;

import net.mouza.security.entity.StationInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface StationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String stationUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_info
     *
     * @mbggenerated
     */
    int insert(StationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_info
     *
     * @mbggenerated
     */
    int insertSelective(StationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_info
     *
     * @mbggenerated
     */
    StationInfo selectByPrimaryKey(String stationUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StationInfo record);
}