package net.mouza.security.dao;

import net.mouza.security.entity.UserOrganizeRelations;
import org.springframework.stereotype.Repository;

@Repository
public interface UserOrganizeRelationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organize_relations
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String recordUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organize_relations
     *
     * @mbggenerated
     */
    int insert(UserOrganizeRelations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organize_relations
     *
     * @mbggenerated
     */
    int insertSelective(UserOrganizeRelations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organize_relations
     *
     * @mbggenerated
     */
    UserOrganizeRelations selectByPrimaryKey(String recordUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organize_relations
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserOrganizeRelations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organize_relations
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserOrganizeRelations record);
}